### PR TITLE
Trims volume list to remove filler values

### PR DESCRIPTION
**Pull request by mitchhentges**
Rather than returning:
```
volume: ChannelVolumes {
    channels: 2,
    values: [Volume(30186), Volume(30186), Volume(0), Volume(0), ..., Volume(0)]
}
```
This PR modifies the output to be:
```
volume: ChannelVolumes {
    channels: 2,
    values: [Volume(30186), Volume(30186)]
}
```

The goal is to make the output more "Rusthonic", but I'm not used to FFI, so I'm not very confident in this change or direction :)

Notes:
* Due to the `Vec`, `ChannelVolumes` can't be `derive(Copy)` anymore
* There's overlap between `channels` and `values`, since `values.len()` has the same information. We could coalesce the values so that: `channels: [Volume(30186), Volume(30186)]`, but then does the `ChannelVolumes` struct make sense? If you replace every instance of `ChannelVolumes` with `Vec<Volume>`, would that mean that we differ too much from the pulseaudio API? Is that a bad thing? Are there other downsides?
* There's other structures that can be simplified in the same way, like `channel_map`
* Honestly, don't worry about closing this PR if it's goofy, I'm just practising my rust :grin:

### CODE REVIEW

**Comment by jnqnfe** [comment]
Quick review:

 1) Your solution is actually incomplete; you've unfortunately introduced bugs as it stands :/
 2) If wanting to truly keep the volume set in line with the number of required channels it might be better to just ditch the `channels` attribute and make the type a more simple wrapper around a `Vec` (i.e. ``struct ChannelVolumes(pub Vec<Volume>)``), since `Vec` already knows its size.
 3) I'm sure there's a method available on `Vec` for copying/appending a slice, which would be preferred over a push loop. Actually, better yet, you can probably just create the `Vec` directly from the slice.
 4) Although I can understand the appeal of shrinking the size of the `ChannelVolumes` struct like you have attempted, `Vec` involves heap memory allocation, which is a relatively expensive operation, and on top of this there's then the effort to copy from the array to the `Vec`. It could be argued perhaps that this negates any benefits you were trying to achieve in shrinking `ChannelVolumes`, and we may be worse off in fact.

Regarding #1, you need to take a closer look at the method implementations of this struct, for instance `init()`, amongst many others. You will see many examples where we simply transmute the `self` reference into a pointer (to the `sys` equivalent (same layout)), passing this through to the pulseaudio C library, whereby pulseaudio operates directly on our struct. If we were to fill in the missing parts of your change, it would involve many cases of converting back and forth between `Vec` and array within these functions, which would be a needlessly inefficient thing to do. The pulseaudio C API is designed to read/write directly with the struct layout that we have. I think that what we might gain from this change is probably far outweighted by the negatives just outlined.

You might wonder about the fact that it compiled cleanly. This is because the `transmute` operation is hiding the problem. I'll see about adding some tests to assert that the object size is identical to that in the sys crate i think for the next release, to help point out such a problem when ever anyone tries changing certain data structures like this that must be identical (i have no better solution yet that allows changing doc comments while directly importing the same struct, and Rust lacks a static_assert()).

On the whole then I think that I'm going to have to reject this particular change.

Thankyou for the effort though :)

**Comment by mitchhentges** [comment]
Thanks for the detailed response! I agree that this PR isn't worth landing.
However, my gut feels that it's a little strange (in Rust) to have a Vec-like data structure whose length isn't known by the structure itself, but rather by a sibling variable.

I'm guessing that the most elegant way of handling this is to update `ChannelVolumes` to implement all the relevant Vec-like methods, while maintaining the same underlying data structure. This way, `transmute` can still operate like normal, but the `channels`+`values` relationship is hidden from consumers of `pulse-binding`? 

What do you think?

**Comment by jnqnfe** [comment]
Vec et. al. are themselves data+length wrappers (essentially). We could hide the inner attributes (make them non-pub) and implement `count()`, `set_count()` methods along with `Deref` and `DerefMut` (if applicable, otherwise `get_slice()` and `get_mut_slice()`) to the inner array.

I'll add that to the todo list to think about :)

**Comment by jnqnfe** [comment]
I've implemented such a solution now on the `next` branch

I think that this is a nice little improvement, certainly more rust-like. Thanks for prompting it :)

**Comment by mitchhentges** [comment]
Looks really interesting, thanks for investigating this further! :heart:

**Comment by jnqnfe** [comment]
fyi, I left this on the `next` branch to wait for a new major release (I've made breaking changes before in minor releases but decided not to with this), expecting it to get bundled into a v3.0 that is intended to include futures support, though i don't know when that might get done.

i've now just bundled the change into the new 2.10 release instead though; i changed it to not make the attributes non-pub, thus preserving backwards compatibility; added deprecation attributes to discourage direct use, and added a new commit to `next` that makes them non-pub (the backwards compatibility break aspect).

so with 2.10+ you can now make use of this improvement :)

**Comment by mitchhentges** [comment]
Sounds great! Thanks again, this was a valuable learning experience for me in seeing how you'd make raw C data more ergonomic :smile:

**Pull request closed without merging**
