### PR TITLE
Add homepage and repo links for published crates

### PR DESCRIPTION
**Pull request by berkus**
There were no links from crates.io to the repo

### CODE REVIEW

**Comment by berkus** [comment]
@jnqnfe hello?

**Comment by jnqnfe** [comment]
sorry for the delay, merged and published in v2.2.2

however the crates.io pages now lack documentation links to docs.rs which needs fixing...

**Comment by jnqnfe** [comment]
^that was an old comment that seemed to have failed to have been submitted correctly a couple days ago

checking crates.io now, the doc links seem to be fine, so I must have just jumped the gun, so please ignore :)
thanks for the patch

**Comment by berkus** [comment]
No problem :)

**Pull request merged**
